contact/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from .views import contact_list, contact_edit, contact_save, contact_delete, Logout
from django.contrib.auth.decorators import login_required

app_name = 'contact'

urlpatterns = [
    url(r'^$', login_required(contact_list.as_view()), name='contact_list'),
    url(r'^new/$', login_required(contact_save.as_view()), name='contact_save'),
    url(r'^(?P<pk>\d+)/edit/$', (contact_edit.as_view()), name='contact_edit'),
    url(r'^logout$', Logout.as_view(), name='logout'),
    url(r'^(?P<pk>\d+)/delete/$',
        login_required(contact_delete.as_view()), name='contact_delete')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('signup.urls')),
    url(r'contact/', include('contact.urls')),
]

signup/urls.py
from django.conf.urls import url
from .views import Register_user, Login_view


urlpatterns = [

    url(r'^$', Login_view.as_view(), name="login_url"),
    url(r'^register$', Register_user.as_view(), name="register"),

]

contact/models.py
from django.db import models

class Contacts(models.Model):
    user = models.ForeignKey('auth.User')
    name = models.CharField(max_length=15,default="")
    mobile = models.CharField(max_length=10,default="")
    address = models.TextField()

    def __str__(self):
        return self.name

signup/models.py
from django.db import models
from django.contrib.auth.models import User


User._meta.get_field('email')._unique = True

contact/forms.py
from django import forms
from .models import Contacts

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contacts
        fields=('name','mobile','description',)

signup/forms.py
from django import forms
from django.contrib.auth.models import User
#from main.validators import validate_email_unique


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, min_length=5)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
   # email = forms.CharField(required=True, validators=[validate_email_unique])

    def clean(self):
        '''
        Overridds the clean method
        '''
        cleaned_data = super(SignupForm, self).clean()
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        if password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        else:
            return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'password', 'confirm_password', 'email')

contact/views.py
from .models import Contacts
from django.contrib.auth.models import User
from django.views.generic import (ListView, DetailView,
                                  UpdateView, DeleteView, CreateView, View)
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from mysite import settings



class contact_list(ListView):

    '''
    Display the Contact list
    '''

    template_name = "contact/contact_list.html"
    context_object_name = "contact"

    def get_queryset(self):
        return Contacts.objects.filter(user=self.request.user)



class contact_edit(UpdateView):

    '''
    Display the Contact edit
    '''
    template_name = "contact/contact_edit.html"
    model =  Contacts
    fields = ['name' , 'mobile' , 'address']
    success_url = reverse_lazy("contact:contact_list")


class contact_delete(DeleteView):

    '''
    Contact delete
    '''

    model = Contacts
    success_url = reverse_lazy("contact:contact_list")


class contact_save(CreateView):

    '''
    Contact save
    '''

    model =  Contacts
    template_name = "contact/contact_save.html"
    fields = ['name' , 'mobile' , 'address']
    success_url = reverse_lazy("contact:contact_list")

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(contact_save, self).form_valid(form)


class Logout(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)

signup/views.py
from django.shortcuts import render
from .forms import SignupForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.views.generic import TemplateView, FormView, View


class Register_user(FormView):

    """
    To add user and email verification
    """

    def post(self, request):

        form = SignupForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.is_active = True
            user.save()
            return HttpResponse(status=200)
        else:
            return HttpResponse(form.errors, status=400)


class Login_view(TemplateView):

    """
    Login user code
    """

    def get(self, request):
        if request.user.is_active:
            return HttpResponseRedirect('contact')
        return render(request, 'signup/login.html')

    def post(self, request):
        username = request.POST['u_name']
        password = request.POST['login_password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print("yes")
            return HttpResponse(status=200)
        else:
            return HttpResponse(status=400)

contact/templates/contact/base.html
{% load staticfiles %}
<html >
    <head>
	<meta charset="UTF-8">
	<title>Contact</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">
	<style>
	 ul.dropdown-menu {
	     background-color: #000;
	 }
	</style>

    </head>
    <body>
	<nav class="navbar navbar-inverse">
	    <div class="container-fluid">

		<!-- Header -->
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" href="{% url 'contact:contact_list' %}" style="font-size:20pt;">Contact</a>
		</div>

		<!-- Contacts -->
		<div class="collapse navbar-collapse" id="topNavBar">

		    <ul class="nav navbar-nav navbar-right">
			<li>
			    <a href="{% url 'contact:contact_save' %}">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Contact
			    </a>
			</li>
			<li class="dropdown" style="right:10px;">
			    <a href="#" class="glyphicon glyphicon-user dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-hidden="true"><span class="caret"></span></a>
			    <ul class="dropdown-menu" role="menu" backgound-color="black">
				<center>
				    <b>
					<li style="color:white;font-size:14px;">
					    <span class="glyphicon glyphicon-user" aria-hidden="true">
					    </span>&nbsp;{{request.user}}
					</li>&nbsp;
					<li style="font-size:14px;">
					    <a href="{% url 'contact:logout' %}" class="logout" style="color:#FFFFFF" >
						<span class="glyphicon glyphicon-off" aria-hidden="false"></span>&nbsp;Logout
					    </a>
					</li>
				    </b>
				</center>
			    </ul>
			</li>
		    </ul>
		</div>
	    </div>
	</nav>
	{% block body %}
	{% endblock %}
    </body>
</html>

contact/templates/contact/contact_edit.html
{% extends 'contact/base.html' %}
{% block body %}
{% if request.user == form.instance.user %}
<div class="container-fluid">
    <div class="col-sm-7 ">
	<div class="panel panel-default">
	    <div class="panel-body" >
		<h2 style="margin-left:5%"><b>Contact Change</b></h2><br><br>
		<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
		    {% include 'contact/form_template.html' %}
		    <div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
			    <button type="submit" class="btn btn-success">Submit</button>
			</div>
		    </div>
		</form>
	    </div>
	</div>
    </div>
</div>
{% else  %}
<h2>
    <span class="label label-warning">
	<strong>Warning!</strong>You don't have permission to view this information
    </span>
</h2>
{% endif %}
{% endblock  %}

contact/templates/contact/contact_list.html
{% extends 'contact/base.html' %}
{% block body %}
<div class="container-fluid">

	{% if contact %}
	<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%" style="padding:5px;">
	    <thead class="thead-inverse">
		<tr>

		    <th>Name</th>
		    <th>mobile</th>
		    <th>address</th>
		    <th>Edit</th>
		    <th>Delete</th>
		</tr>
	    </thead>
	    <tbody>
		{% for contacts in contact %}
		<tr>
		    <th>{{contacts.name}}</th>
		    <th>{{contacts.mobile}}</th>
		    <th>{{contacts.address}}</th>
		    <th><a align="right" class="btn btn-default" href="{% url 'contact:contact_edit' contacts.id %}"  ><span class="glyphicon glyphicon-pencil"></span></a></th>
		    <th>
			<form action="{% url 'contact:contact_delete'  contacts.id %}" method="post" style="display: inline;">
			    {% csrf_token %}
			    <input type="hidden" name="album_id" value="{{  contacts.id }}" />
			    <button type="submit" class="btn btn-default btn-sm">
				<span class="glyphicon glyphicon-trash"></span>
			    </button>
			</form></th>
		</tr>
		{% endfor %}
	    </tbody>
	</table>
		
		{% endif %}

</div>
<script>
$(document).ready(function() {

     $('#datatable').dataTable();
 });
</script>
<script language="JavaScript" src="https://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript"></script>
<script language="JavaScript" src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
{% endblock  %}

contact/templates/contact/contact_save.html
{% extends 'contact/base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="col-sm-7 centered">
	<div class="panel panel-default">
	    <div class="panel-body" >
		<h2 style="margin-left:5%"><b>Add new Contact</b></h2><br><br>
		<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
		    {% include 'contact/form_template.html' %}
		    <div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
			    <button type="submit" class="btn btn-success">Submit</button>
			</div>
		    </div>
		</form>
	    </div>
	</div>
    </div>
</div>
{% endblock  %}

contact/templates/contact/form_template.html
{% for field in form %}
<div class="form-group">
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-5">{{ field }}</div>
    <div class="col-sm-5">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
</div>
{% endfor %}

signup/templates/signup/login.html
{% load staticfiles %}
<html>
    <head>
	<title>Login</title>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{% static 'css/signup.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
	 <script src="{% static 'js/login.js' %}"></script>
	<script src="https://cdn.rawgit.com/t4t5/sweetalert/master/dist/sweetalert.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/t4t5/sweetalert/master/dist/sweetalert.css">

	<style>
	 body{
	     background-image: url({% static "order.jpg" %});
	     background-size: cover;
	     background-position: top center;
	     background-repeat: no-repeat;
	     background-attachment: fixed;
	 }
	 p{
	     color:red;
	     font-size:small;
	 }
	</style>

    </head>
    <body>
	<div class="container-fluid">
	    <div class="row">

		<div class="col-md-3">
		    <div class="container">
			<!-- Trigger the modal with a button -->&nbsp;&nbsp;<br>
			&nbsp;&nbsp;<br>
			<button type="button" class="btn Login-btn btn-success btn-xl" data-toggle="modal" data-keyboard="true" id="login_b">Login</button>
			<button type="button" class="btn signup-btn btn-primary btn-xl" data-toggle="modal" id="registration_b" data-keyboard="true">Signup</button></a>

		    <!-- Modal -->
			<div class="modal fade" id="Registration" role="dialog" tabindex="-1">
			    <div class="modal-dialog modal-md">
				<div class="modal-content">
				    <div class="modal-header">
					<button type="button" id="close" class="close" data-dismiss="modal">×</button>
					<center> <b> <h3 class="modal-title">Registration</h3></b> </center>
				    </div>
				    <div class="modal-body" style = "background-color:#E0FFFF;">
					<center>
					    <div style= "margin-top:1px;">
						<form style="align:center;" id ="register_form" method="POST" action="">{% csrf_token %}
						    <table cellspacing = "5" cellpadding = "5">
							<tr>
							    <td></td>
							</tr>
							<tr>
							    <td>Username<span style="color:red">*</span></td>
							    <td><input type="text" id="username" name="username" value="" class="form-control" placeholder="Enter username"></td>

							</tr>

							<tr>
							    <td></td>
							    <td><p id="username_error"></p></td>
							</tr>

							<tr>
							    <td>

							    </td>
							</tr>
							<td>Email<span style="color:red">*</span></td>
							<td><input type="text" id="email" name="email" value="" class="form-control" placeholder="Enter email address"></td>

							</tr>

							<tr>
							    <td></td>
							    <td><p id="email_error"></p></td>
							</tr>
							<tr>
							    <td>

							    </td>
							</tr>
							<tr>
							    <td>Password<span style="color:red">*</span></td>
							    <td><input type="password" id="password" name="password" value="" class="form-control" placeholder="Enter Password"></td>

							</tr>
							<tr>
							    <td>

							    </td>
							</tr>
							<tr>
							    <td></td>
							    <td><p id="password_error"></p></td>
							</tr>
							<tr>
							    <td>Confirm password<span style="color:red">*</span></td>
							    <td><input type="password" id="confirm_password" name="confirm_password" value="" class="form-control" placeholder="Enter confirm passwrd">
							    </td>

							</tr>
							<tr>
							    <td>

							    </td>
							</tr>

							<tr>
							    <td></td>
							    <td><p id="confirm_password_error"></p></td>
							</tr>

							<tr>
							    <td colspan="6" align="center"><input type="button" id="register"  name="register" value="register" class="btn btn-success" ></td>
							    <td>

							    </td>
							</tr>
							<tr>
							    <td>&nbsp;</td>
							</tr>
							<tr>
							    <td></td>
							    <td> <div id="wait" style="display:none;width:22px;height:22px;border:0px solid black;">
								Loading..<img src="{% static "demo_wait.gif" %}" width="20" height="20" /></div>
							    </td>
							</tr>
						    </table>
						    <br><br>
						    <p id="error" style="color:red;"></p>
						</form>
					    </div>
					</center>
				    </div>
				    <div class="modal-footer">

				    </div>
				</div>
			    </div>
			</div>

			<!-- Login Modal -->
			<div class="modal fade" id="myModal" role="dialog" tabindex="-1">
			    <div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
				    <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h3 class="modal-title" style="font-family:'Rock-Salt', cursive;" align="center">Login</h3>
				    </div>
				    <div class="modal-body" style="background-color:#E0FFFF;">
					<form id="login_form" method="post" action="" >{% csrf_token %}
					    <center>
						<br>
						<label>Username:<span style="color:red">*</span></label>&nbsp;&nbsp;&nbsp;&nbsp;
						<input type="text" id="u_name" autofocus="autofocus" class="form-control form-control-inline" name="u_name" placeholder="Enter username"><br><br>
						<label>Password:<span style="color:red">*</span></label>&nbsp;&nbsp;&nbsp;&nbsp;
						<input type="password" id="login_password" class="form-control form-control-inline" name="login_password" placeholder="Enter password"><br><br>
						<input type="button" id="login" class="btn btn-success btn-md" value="Login" ><br><br>
						<p id="error_login" style="color:red;"></p>
					    </center>
					</form>
				    </div>
				</div>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	</div>
    </body>
</html>